### ISSUE TITLE
more 3ds error codes

### ISSUE THREAD

**Issue by RISC-VLIW** [PretendoNetwork/Bandwidth#21]
Hello, I wanted to open up an issue to supply a few error codes and fixes that can hopefully be added to bandwidth's database:

012-1511 and 000-0000 share a fix due to them appearing sequentially: remove rev.pem, I'm not 100% sure of the cause, but I think it's a conflict of the certificates, but idk.

022-2402: make an account on the pretendo website and use that to login, I'm not sure why it's caused, as some people can create accounts through their console, yet some cannot.

022-5515: ensure you're logged into your PNID, if you are, the account servers may be down.

these are a few errors I've encountered that I am fairly confident in the fixes in, if there's any problems please let me know!

**Comment by jonbarrow** [comment]
Information and issues regarding error codes should now be moved to https://github.com/PretendoNetwork/error-codes
